# Variables_1주차 정리 

python및 모든 프로그래밍에서 = 은 '같다'가 아닌 assign의 의미를 가진다. (같다는 ==으로 표기한다) 
print( )는 괄호 안에 있는 것을 보여달라는 의미.
type는 a라는 변수의 종류를 보여달라는 것을 의미한다. type라는 함수를 사용하게 되면 class '___ 가 나오게 되는데, 그 종류에는 int(정수) float(소수) str(''로 묶인 단어) 등이 있다. 

In [17]:
a = 1; print(type(a))

<class 'int'>


int는 필요에 따라 float로 바꿀 수도 있다. 

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


마찬가지로 float 또한 int로 바꿀 수 있는데, 이 경우 소수점 아래의 숫자가 날라간 형태로 표시된다. 

In [1]:
a = 1.2; a = int(a); print(type(a))
a

<class 'int'>


1

앞서 말한 str이라는 class는 ''로 묶인 일종의 단어를 지칭한다. 즉, 아래의 경우에서 '123'은 숫자 백이십삼이 아닌 문자 그대로의 1 2 3이 묶인 형태로 인식된다. str에서 각각의 항을 보기 위해서는 a[1]과 같이 a의 n번째 항을 지정해주면 되는데, 이 때 주의해야할 점은 [0]이1번째 항이고 [-1]은 마지막 항이라는 점이다. 

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


str은 list로 바꿀 수 있다. 이경우에는 [ ] 안에 str의 각각의 항이 ''에 묶여 들어가게 된다. 

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


list는 그 안의 항으로 별도의 list를 가질 수도 있다.
list 또한 [ ]에 넣어서 각각의 항을 불러 올 수 있고, 그 안의 항 또한 불러올 수 있다. 

In [10]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2]); print(a[2][-1])

<class 'list'>
1
2
[3, '4']
4


( ) 안에 존재하는 값의 나열은 tuple이라고 부르는데, 이는 바꾸기 어려운 list라고 생각하면 편하다. 

In [8]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2]); 


<class 'tuple'>
1
2
[3, '4']
4


{ } 안에 "a" :"apple"의 형태로 각각 앞의 변수가 무엇인지 사전처럼 정의 해놓은 것을 dict라고 한다. 
마찬가지로, a["a"]와 같이 dict안의 특정한 a라는 값이 무엇이 assign되어 있는지 확인 할 수 있다. 

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


아래와 같은 a를 tuple이라고 한다. 

In [2]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

import - 하드디스크에 있는 수식을 메모리로 띄우는 것. numpy - 행렬의 형태를 사용하게끔 하는 것. 
as np - numpy의 이름을 np라고 지정하는 것.이를 쓰지 않는다면 library이름.function이름(a)라고 써야하게 된다. 
ndarray - n차 array라는 뜻.

In [3]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


원래 아는 행렬의 곱셈에서는 (2x3 * 2x3)의 곱셈이 안되지만 array에서는 같은 자리(element)끼리 곱하면 된다.

In [4]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


numpy안에 matrix라는 함수도 존재한다. matrix를 사용해보면, array와 같은 형태지만 matrix(=행렬)로 바꼈다. 

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


원래 행렬의 곱셈과 같이 당연히 c* c가 불가능하게 된다. 

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

t도 numpy의 함수 중 하나로, transpose를 의미한다. (2x3 * 3x2)이기 때문에 이제 (2x2)행렬로 곱셈이 가능하다 

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

아래의 str인데, 이를 다루는 자세한 사항은 string파일을 참조하도록 한다. 

In [6]:
s = 'abcdef'

In [7]:
print(type(s))

<class 'str'>
